#!/usr/bin/env python3
"""Generate LxveOS per-board build inputs from the cyd_boards.json SSOT.

Emits, for every board in the manifest:
  boards/<id>/sdkconfig.defaults   IDF_TARGET, flash/PSRAM/partition/optimize, LXVEOS_HAS_* feature gates
  boards/<id>/board_info.h         runtime constants the BSP needs (driver, w/h, runtime_probe, ui_profile)
and (re)writes CMakePresets.json (one configure preset per board, chained sdkconfig.defaults).

Adding a board = one JSON edit + re-run. The manifest stays the single source shared with Cyber Controller.
No ESP-IDF required to run this (pure Python). See command-center/projects/lxveos/build-architecture.md.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "cyd_boards.json")

FLASH = {"4MB": "CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y",
         "8MB": "CONFIG_ESPTOOLPY_FLASHSIZE_8MB=y",
         "16MB": "CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y"}
# feature keys whose value is boolean True -> compile the module in (HAS_*). "addon" strings are
# left out (not compiled by default; unlocked at runtime by the capability probe).
HAS_KEYS = ("wifi", "ble", "bt_classic", "display", "ir", "gps", "subghz", "nrf24", "nfc", "storage")


def sdkconfig_lines(bid, b):
    build = b.get("build", {})
    out = ['# GENERATED from cyd_boards.json by scripts/gen_board_configs.py — do not edit by hand.',
           f'# board: {bid}']
    out.append(f'CONFIG_IDF_TARGET="{build.get("idf_target", b.get("chip", "esp32"))}"')
    fs = b.get("flash_size")
    if fs in FLASH:
        out.append(FLASH[fs])
    csv = build.get("partition_csv")
    if csv:
        out.append("CONFIG_PARTITION_TABLE_CUSTOM=y")
        out.append(f'CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="{csv}"')
    if build.get("psram"):
        out.append("CONFIG_SPIRAM=y")
        if build.get("psram_mode") == "oct":
            out += ["CONFIG_SPIRAM_MODE_OCT=y", "CONFIG_SPIRAM_SPEED_80M=y",
                    "CONFIG_SPIRAM_XIP_FROM_PSRAM=y"]
    out.append("CONFIG_COMPILER_OPTIMIZATION_PERF=y" if build.get("optimize") == "perf"
               else "CONFIG_COMPILER_OPTIMIZATION_SIZE=y")
    feats = b.get("features", {})
    for k in HAS_KEYS:
        if feats.get(k) is True:
            out.append(f"CONFIG_LXVEOS_HAS_{k.upper()}=y")
    return "\n".join(out) + "\n"


def board_info_h(bid, b):
    d = b.get("display", {})
    present = bool(d.get("present"))
    def s(v):  # C string or NULL
        return "NULL" if v is None else f'"{v}"'
    lines = ["#pragma once",
             "// GENERATED from cyd_boards.json by scripts/gen_board_configs.py — do not edit by hand.",
             f'#define LXVEOS_BOARD_ID          "{bid}"',
             f'#define LXVEOS_CHIP              "{b.get("chip","")}"',
             f'#define LXVEOS_UI_PROFILE        "{b.get("ui_profile","headless")}"',
             f'#define LXVEOS_HAS_DISPLAY       {1 if present else 0}']
    if present:
        lines += [
            f'#define LXVEOS_DISP_DRIVER       {s(d.get("driver"))}',
            f'#define LXVEOS_DISP_RUNTIME_PROBE {1 if d.get("runtime_probe") else 0}',
            f'#define LXVEOS_DISP_W            {d.get("native_w", 0)}',
            f'#define LXVEOS_DISP_H            {d.get("native_h", 0)}',
            f'#define LXVEOS_DISP_BUS          {s(d.get("bus"))}',
            f'#define LXVEOS_DISP_BACKEND      {s(d.get("hal_backend"))}',
        ]
    return "\n".join(lines) + "\n"


def preset(bid, b):
    build = b.get("build", {})
    target = build.get("idf_target", b.get("chip", "esp32"))
    bd = f"${{sourceDir}}/build/{bid}"
    chain = f"sdkconfig.defaults;sdkconfig.defaults.{target};boards/{bid}/sdkconfig.defaults"
    return {
        "name": bid,
        "displayName": bid,
        "binaryDir": bd,
        "cacheVariables": {
            "IDF_TARGET": target,
            "LXVEOS_BOARD": bid,
            "SDKCONFIG": f"{bd}/sdkconfig",
            "SDKCONFIG_DEFAULTS": chain,
        },
    }


def main():
    with open(MANIFEST, encoding="utf-8") as f:
        boards = json.load(f)["boards"]
    presets = []
    for bid, b in boards.items():
        bdir = os.path.join(ROOT, "boards", bid)
        os.makedirs(bdir, exist_ok=True)
        with open(os.path.join(bdir, "sdkconfig.defaults"), "w", encoding="utf-8", newline="\n") as f:
            f.write(sdkconfig_lines(bid, b))
        with open(os.path.join(bdir, "board_info.h"), "w", encoding="utf-8", newline="\n") as f:
            f.write(board_info_h(bid, b))
        presets.append(preset(bid, b))
    doc = {
        "version": 4,
        "cmakeMinimumRequired": {"major": 3, "minor": 24, "patch": 0},
        "_comment": "GENERATED by scripts/gen_board_configs.py from cyd_boards.json. ESP-IDF v6.0 has no preset 'inherits' -> chains flattened.",
        "configurePresets": presets,
    }
    with open(os.path.join(ROOT, "CMakePresets.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump(doc, f, indent=2)
        f.write("\n")
    print(f"generated {len(presets)} boards -> boards/*/ + CMakePresets.json")


if __name__ == "__main__":
    main()
